const express=require('express'),cors=require('cors'),bcrypt=require('bcryptjs'); const pool=require('./db'); const {sign,requireAuth}=require('./auth');
const app=express(); app.use(cors({origin:true})); app.use(express.json());
const arr=v=>Array.isArray(v)?v:[];
function normalize(s){return String(s||'').toLowerCase().replace(/[^a-z0-9+#. ]/g,'').trim()}
function scoreEvent(e,p){
 const skills=arr(p?.skills).map(normalize), interests=arr(p?.interests).map(normalize), required=arr(e.required_skills).map(normalize);
 const skillHits=required.filter(x=>skills.some(s=>s===x||s.includes(x)||x.includes(s))).length; const skillScore=required.length?skillHits/required.length:0.5;
 const text=normalize([e.event_name,e.category,e.event_type,...required].join(' ')); const intHits=interests.filter(x=>text.includes(x)).length; const interestScore=interests.length?Math.min(1,intHits/Math.min(2,interests.length)):0.5;
 const career=normalize(p?.career_goal); const careerScore=career && text.includes(career.split(' ')[0])?1:(career&&(['ai','ml','data','software','developer','engineer'].some(k=>career.includes(k)&&text.includes(k)))?.8:.4);
 const loc=normalize(p?.location), eloc=normalize(e.location); const locationScore=eloc==='online'||eloc==='hybrid'||!loc||eloc.includes(loc)?1:.2;
 const eligibility=1; const total=Math.round((skillScore*.55+interestScore*.2+careerScore*.15+locationScore*.1)*100);
 const reasons=[]; if(skillHits) reasons.push(`Your skills ${required.filter(x=>skills.some(s=>s===x||s.includes(x)||x.includes(s))).slice(0,3).join(', ')} match`); if(intHits) reasons.push('Your interests align with this event'); if(careerScore>=.8) reasons.push('Career goal is aligned'); if(locationScore===1) reasons.push('Location or online preference matched'); reasons.push('Eligibility appears compatible');
 return {...e,match_score:Math.min(99,Math.max(40,total)),skill_score:Math.round(skillScore*100),interest_score:Math.round(interestScore*100),career_score:Math.round(careerScore*100),location_score:Math.round(locationScore*100),matched_skills:required.filter(x=>skills.some(s=>s===x||s.includes(x)||x.includes(s))),missing_skills:required.filter(x=>!skills.some(s=>s===x||s.includes(x)||x.includes(s))),reasons};
}
app.get('/api/health',(req,res)=>res.json({ok:true}));
app.post('/api/auth/login',async(req,res)=>{try{const {email,password}=req.body; const q=await pool.query('SELECT * FROM users WHERE email=$1',[email]);if(!q.rowCount)return res.status(401).json({error:'Invalid email or password'});const u=q.rows[0];if(!await bcrypt.compare(password,u.password_hash))return res.status(401).json({error:'Invalid email or password'});res.json({token:sign(u),user:{id:u.id,name:u.name,email:u.email,role:u.role}})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/auth/signup',async(req,res)=>{try{const {name,email,password,role='student'}=req.body;const hash=await bcrypt.hash(password,10);const q=await pool.query('INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4) RETURNING *',[name,email,hash,role]);const u=q.rows[0];if(role==='student')await pool.query('INSERT INTO student_profiles(user_id,skills,interests) VALUES($1,ARRAY[]::text[],ARRAY[]::text[])',[u.id]);if(role==='organizer')await pool.query('INSERT INTO organizers(user_id,organization_name) VALUES($1,$2)',[u.id,name]);res.json({token:sign(u),user:{id:u.id,name:u.name,email:u.email,role:u.role}})}catch(e){res.status(400).json({error:e.code==='23505'?'Email already registered':e.message})}});
app.post('/api/auth/reset-password',async(req,res)=>{try{const {email,newPassword}=req.body;if(!email||!newPassword)return res.status(400).json({error:'Email and new password are required'});const q=await pool.query('SELECT * FROM users WHERE email=$1',[email]);if(!q.rowCount)return res.status(404).json({error:'User with this email was not found'});const hash=await bcrypt.hash(newPassword,10);await pool.query('UPDATE users SET password_hash=$1 WHERE email=$2',[hash,email]);res.json({message:'Password updated successfully! Please sign in with your new password.'})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/profile',requireAuth,async(req,res)=>{const q=await pool.query('SELECT u.id,u.name,u.email,u.role,p.* FROM users u LEFT JOIN student_profiles p ON p.user_id=u.id WHERE u.id=$1',[req.user.id]);res.json(q.rows[0])});
app.put('/api/profile',requireAuth,async(req,res)=>{const {name,department,year,location,career_goal,experience_level,skills,interests}=req.body;await pool.query('UPDATE users SET name=$1 WHERE id=$2',[name,req.user.id]);await pool.query(`INSERT INTO student_profiles(user_id,department,year,location,career_goal,experience_level,skills,interests) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(user_id) DO UPDATE SET department=$2,year=$3,location=$4,career_goal=$5,experience_level=$6,skills=$7,interests=$8`,[req.user.id,department,year,location,career_goal,experience_level,arr(skills),arr(interests)]);res.json({ok:true})});
app.get('/api/events',async(req,res)=>{const {q,category,mode,free}=req.query;let sql='SELECT * FROM events WHERE 1=1',v=[];if(q){v.push('%'+q+'%');sql+=` AND (event_name ILIKE $${v.length} OR description ILIKE $${v.length})`}if(category&&category!=='All'){v.push(category);sql+=` AND category=$${v.length}`}if(mode){v.push(mode);sql+=` AND mode=$${v.length}`}if(free==='true'){sql+=' AND is_free=true'}sql+=' ORDER BY start_date NULLS LAST LIMIT 100';res.json((await pool.query(sql,v)).rows)});
app.get('/api/events/:id',async(req,res)=>{const q=await pool.query('SELECT * FROM events WHERE id=$1',[req.params.id]);if(!q.rowCount)return res.status(404).json({error:'Event not found'});res.json(q.rows[0])});
app.get('/api/recommendations',requireAuth,async(req,res)=>{const p=(await pool.query('SELECT * FROM student_profiles WHERE user_id=$1',[req.user.id])).rows[0]||{};const ev=(await pool.query('SELECT * FROM events WHERE status <> $1 OR status IS NULL',['Completed'])).rows;res.json(ev.map(e=>scoreEvent(e,p)).sort((a,b)=>b.match_score-a.match_score).slice(0,20))});
app.get('/api/events/:id/recommendation',requireAuth,async(req,res)=>{const e=(await pool.query('SELECT * FROM events WHERE id=$1',[req.params.id])).rows[0];const p=(await pool.query('SELECT * FROM student_profiles WHERE user_id=$1',[req.user.id])).rows[0]||{};res.json(scoreEvent(e,p))});
app.post('/api/events/:id/save',requireAuth,async(req,res)=>{try{const check=await pool.query('SELECT * FROM saved_events WHERE user_id=$1 AND event_id=$2',[req.user.id,req.params.id]);if(check.rowCount){await pool.query('DELETE FROM saved_events WHERE user_id=$1 AND event_id=$2',[req.user.id,req.params.id]);return res.json({saved:false})}else{await pool.query('INSERT INTO saved_events(user_id,event_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.user.id,req.params.id]);return res.json({saved:true})}}catch(e){res.json({saved:true})}});
app.post('/api/events/:id/register',requireAuth,async(req,res)=>{await pool.query('INSERT INTO registrations(user_id,event_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.user.id,req.params.id]);res.json({registered:true})});
app.get('/api/registrations',requireAuth,async(req,res)=>{res.json((await pool.query('SELECT e.*,r.registered_at,r.status AS registration_status FROM registrations r JOIN events e ON e.id=r.event_id WHERE r.user_id=$1 ORDER BY r.registered_at DESC',[req.user.id])).rows)});
app.get('/api/saved',requireAuth,async(req,res)=>{res.json((await pool.query('SELECT e.*,s.saved_at,true AS is_saved FROM saved_events s JOIN events e ON e.id=s.event_id WHERE s.user_id=$1 ORDER BY s.saved_at DESC',[req.user.id])).rows)});
app.get('/api/saved-events',requireAuth,async(req,res)=>{res.json((await pool.query('SELECT e.*,s.saved_at,true AS is_saved FROM saved_events s JOIN events e ON e.id=s.event_id WHERE s.user_id=$1 ORDER BY s.saved_at DESC',[req.user.id])).rows)});
app.get('/api/skill-gap/:eventId',requireAuth,async(req,res)=>{const e=(await pool.query('SELECT * FROM events WHERE id=$1',[req.params.eventId])).rows[0];const p=(await pool.query('SELECT * FROM student_profiles WHERE user_id=$1',[req.user.id])).rows[0]||{};const r=scoreEvent(e,p);res.json({event:e,matched:r.matched_skills,missing:r.missing_skills,resources:r.missing_skills.map(s=>({skill:s,title:`${s} Fundamentals`,description:`Beginner-to-intermediate learning path for ${s}.`,url:`https://www.google.com/search?q=${encodeURIComponent(s+' fundamentals course')}`}))})});
app.get('/api/organizer/dashboard',requireAuth,async(req,res)=>{let o=(await pool.query('SELECT id FROM organizers WHERE user_id=$1',[req.user.id])).rows[0];if(!o){const ins=await pool.query('INSERT INTO organizers(user_id,organization_name) VALUES($1,$2) RETURNING id',[req.user.id,'EventIQ Organizer']);o=ins.rows[0]}const events=(await pool.query('SELECT * FROM events WHERE organizer_id=$1 ORDER BY created_at DESC',[o?.id||-1])).rows;const registrations=(await pool.query('SELECT COUNT(*)::int c FROM registrations r JOIN events e ON e.id=r.event_id WHERE e.organizer_id=$1',[o?.id||-1])).rows[0]?.c||0;res.json({stats:{total:events.length,active:events.filter(e=>!['Completed'].includes(e.status)).length,registrations},events})});
app.get('/api/organizer/events',requireAuth,async(req,res)=>{let o=(await pool.query('SELECT id FROM organizers WHERE user_id=$1',[req.user.id])).rows[0];if(!o){const ins=await pool.query('INSERT INTO organizers(user_id,organization_name) VALUES($1,$2) RETURNING id',[req.user.id,'EventIQ Organizer']);o=ins.rows[0]}const events=(await pool.query('SELECT * FROM events WHERE organizer_id=$1 ORDER BY created_at DESC',[o?.id||-1])).rows;res.json(events)});
app.post('/api/organizer/events',requireAuth,async(req,res)=>{let o=(await pool.query('SELECT id FROM organizers WHERE user_id=$1',[req.user.id])).rows[0];if(!o){const ins=await pool.query('INSERT INTO organizers(user_id,organization_name) VALUES($1,$2) RETURNING id',[req.user.id,'EventIQ Organizer']);o=ins.rows[0]}const x=req.body;const titleVal=x.event_name||x.title||'New Event';const q=await pool.query(`INSERT INTO events(event_code,title,description,event_type,category,mode,location,start_date,end_date,registration_fee,is_free,organizer_id,organizer_name,required_skills,target_audience,difficulty,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'EventIQ Organizer',$13,$14,$15,$16) RETURNING *`,['NEW-'+Date.now(),titleVal,x.description||'',x.event_type||'Event',x.category||'Academic & Professional',x.mode||'Online',x.location||'Online',x.start_date||new Date().toISOString().split('T')[0],x.end_date||new Date().toISOString().split('T')[0],x.registration_fee_inr||x.registration_fee||0,!!x.is_free,o.id,arr(x.required_skills),arr(x.target_audience),x.difficulty||'Intermediate',x.status||'Upcoming']);const row=q.rows[0];res.json({...row,event_name:row.title})});
app.post('/api/organizer/analyze',requireAuth,async(req,res)=>{const x=req.body;const text=normalize([x.event_name||x.title,x.description,...arr(x.required_skills)].join(' '));let category='Academic & Professional',smart='General Student Event';if(/hack|code|programming/.test(text)){smart='AI / Coding Hackathon';category='Academic & Professional'}else if(/workshop|training|sttp/.test(text)){smart='Technical Workshop'}else if(/conference|summit/.test(text)){smart='Technology Conference'}const skills=[...new Set([...arr(x.required_skills),...(text.match(/python|machine learning|ai|llm|nlp|cybersecurity|iot|data science|programming|cloud/gi)||[]).map(s=>s[0].toUpperCase()+s.slice(1))])];const target=/ai|machine|llm|data/.test(text)?['AI & Data Science','CSE','IT','ECE']:['College Students'];res.json({smart_category:smart,skill_tags:skills,target_audience:target,difficulty:x.difficulty||'Intermediate',career_relevance:/ai|ml|machine/.test(text)?['AI Engineer','ML Engineer','Data Scientist']:['Software Developer','Researcher'],quality_score:Math.min(98,70+skills.length*5),confidence:0.91,missing_information:[!x.location?'Location':null,!x.start_date?'Date':null,!x.required_skills?.length?'Required skills':null].filter(Boolean),insight:'Your event has strong relevance for the identified student audience.'})});
app.listen(process.env.PORT||4000,()=>console.log('EventIQ API running on '+(process.env.PORT||4000)));
